{
  parserClass="com.simpleplugin.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.simpleplugin.psi"
  psiImplPackage="com.simpleplugin.psi.impl"

  elementTypeHolderClass="com.simpleplugin.psi.SimpleTypes"
  elementTypeClass="com.simpleplugin.psi.SimpleElementType"
  tokenTypeClass="com.simpleplugin.psi.SimpleTokenType"

  tokens = [
    SEMICOLON =';'
    EQ = '='

    number="regexp:\d+"
    id="regexp:\w+"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"

    line_comment="regexp://.*"
    block_comment="regexp:/\*(.|\n)*\*/"
  ]

}


simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF|property1)

property ::= (KEY? SEPARATOR VALUE?) | KEY

private item_ ::= property1 {
recoverWhile=top_recover
}

private top_recover ::= !(id "=")

property1 ::= expr

expr::= id "=" number ";"





